"""empty message

Revision ID: 03b3ce065853
Revises: ba463a51c706
Create Date: 2025-11-04 18:41:16.152581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b3ce065853'
down_revision = 'ba463a51c706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
