"""empty message

Revision ID: 0e2a97c3af24
Revises: 9c749bb9dd8f
Create Date: 2026-01-17 11:07:50.391389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2a97c3af24'
down_revision = '9c749bb9dd8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_authorliked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('is_authorliked')
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
