"""empty message

Revision ID: 1cfe17a91a92
Revises: ade3483a707b
Create Date: 2025-11-22 11:23:54.754053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfe17a91a92'
down_revision = 'ade3483a707b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_notification_recipient_id", 'user', ['recipient_id'], ['id'])
        batch_op.create_foreign_key("fk_notification_poll_id", 'poll', ['poll_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poll_id')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_read')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
