"""empty message

Revision ID: 4d4512e64e73
Revises: 0e2a97c3af24
Create Date: 2026-01-27 18:05:39.994680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4512e64e73'
down_revision = '0e2a97c3af24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


