"""empty message

Revision ID: 7be986c3f47c
Revises: 14f293b0b4ca
Create Date: 2025-10-18 11:26:40.703680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be986c3f47c'
down_revision = '14f293b0b4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'poll_option', ['option_id'], ['id'])
        batch_op.drop_column('vote')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('option_id')

    op.drop_table('poll_option')
    # ### end Alembic commands ###
